name: 06 - Activity Types
on:
    pull_request:
        branches:
            - develop
        types:
            - opened
            - synchronize 

jobs:
    muestra-echo:
        runs-on: ubuntu-latest
        steps:
            - name: mostrar echo        
              run: 
                echo "Running whenever a PR is opened or synchronized AND base branch is develop"            
