name: Build APP

on:
   workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest   
        defaults:
            run:
                working-directory: my-appluis
        steps:
            - name: descargar codigo
              uses: actions/checkout@v4
              
            - name: Instalar Node
              uses: actions/setup-node@v4
              
            - name: Instalar dep
              run: npm ci
            
            - name: Ejecutar test
              run: npm test



